from pydantic import BaseModel


class CertificateData(BaseModel):
    certificateFormat: str = "format1"

    # ── Format 1 fields ───────────────────────────────────
    billingCustomerName: str = ""
    billingAddress: str = ""
    billingState: str = ""
    billingPincode: str = ""
    billingCountry: str = ""
    shippingCustomerName: str = ""
    shippingAddress: str = ""
    shippingState: str = ""
    shippingPincode: str = ""
    shippingCountry: str = ""
    dateOfDispatch: str = ""
    invoicePONumber: str = ""
    warrantyPeriod: str = ""
    materialPartName: str = ""
    quantityKWp: str = ""
    remarks: str = ""

    # ── Format 2 fields ───────────────────────────────────
    f2ProjectName: str = ""
    f2Client: str = ""
    f2SolarConsultant: str = ""
    f2SolarDeveloper: str = ""
    f2MainContractor: str = ""
    f2Location: str = ""
    f2ProductDescription: str = ""
    f2ProductWarranty: str = ""
    f2DesignWarranty: str = ""
    f2WarrantyPeriodNote: str = ""
    f2DateOfIssue: str = ""

    # ── Format 3 (Test Certificate) fields ────────────────
    tcRefNumber: str = ""
    tcDate: str = ""
    tcCustomerName: str = ""
    tcCustomerAddress: str = ""
    tcCustomerGstin: str = ""
    tcProjectName: str = ""
    tcSupplierName: str = "SUNRACK TECHNOLOGIES LLP"
    tcSupplierAddress: str = "Flat no. 13 A/18 Krishna Gopal Krishna Nagar, Khairapada, Boisar, Dist. Palghar, Maharashtra-401501"
    tcSupplierGstin: str = "27AEEFS1875H1ZR"
    tcPoNumber: str = ""
    tcPoDate: str = ""
    tcDispatchDate: str = ""
    tcMaterialPartName: str = ""
    tcQuantityKWp: str = ""
    tcRemarks: str = ""
    tcSi: str = ""
    tcMg: str = ""
    tcFe: str = ""
    tcOther: str = ""
    tcAl: str = ""
    tcBHN: str = ""
    tcHV10: str = ""
